[tool.poetry]
name = "template"
version = "0.1.0"
description = ""
authors = ["cashmere53 <15913755+cashmere53@users.noreply.github.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
ruff = "^0.0.282"
mypy = "^1.4.1"
pytest = "^7.4.0"


[tool.poetry.scripts]
tmp = "template.__main__:main"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
target-version = ["py311"]
line-length = 120


[tool.ruff]
select = ["ALL"]
ignore = ["T201", "D203", "D212", "ERA001", "D1", "ANN"]
unfixable = ["F401", "F841"]
line-length = 120


[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
strict_equality = true


[tool.pytest.ini_options]
testpaths = ["tests"]
# filterwarnings = ["ignore::DeprecationWarning",]
