[tool.poetry]
name = "template"
version = "0.1.0"
description = ""
authors = ["cashmere53 <15913755+cashmere53@users.noreply.github.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
black = "^22.12.0"
mypy = "^0.991"
isort = "^5.11.4"
pyproject-flake8 = "^6.0.0"
flake8-bugbear = "^22.12.6"


[tool.poetry.scripts]
tmp = "template.__main__:main"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
target-version = ["py311"]
line-length = 88


[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_local_folder = ["config",]


[tool.flake8]
max-line-length = 88
max-complexity = 10
count = true
ignore = "E203,E266,W503,"
per-file-ignores = [
    "__init__.py:F401",
]


[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
strict_equality = true


[tool.pytest.ini_options]
testpaths = ["tests",]
# filterwarnings = ["ignore::DeprecationWarning",]
