[tool.poetry]
name = "template"
version = "0.1.0"
description = ""
authors = ["cashmere53 <15913755+cashmere53@users.noreply.github.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.12"


[tool.poetry.group.dev.dependencies]
black = "^23.10.1"
ruff = "^0.1.4"
mypy = "^1.6.1"
pytest = "^7.4.3"
pytest_cov = "^4.1.0"
poethepoet = "^0.24.2"


[tool.poetry.scripts]
tmp = "template.__main__:main"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
target-version = ["py311"]
line-length = 120


[tool.ruff]
select = ["ALL"]
ignore = ["T201", "D203", "D212", "ERA001", "D1", "ANN"]
unfixable = ["F401", "F841"]
line-length = 120


[tool.ruff.pydocstyle]
convention = "google"


[tool.ruff.per-file-ignores]
"tests/**/*.py" = ["S101"]


[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict = true
# warn_unused_configs = true
# disallow_any_generics = true
# disallow_subclassing_any = true
# disallow_untyped_calls = true
# disallow_untyped_defs = true
# disallow_incomplete_defs = true
# check_untyped_defs = true
# disallow_untyped_decorators = true
# warn_redundant_casts = true
# warn_unused_ignores = true
# warn_return_any = true
# no_implicit_reexport = true
# strict_equality = true
# extra_checks = true


[tool.pytest.ini_options]
testpaths = ["tests"]
# filterwarnings = ["ignore::DeprecationWarning",]


[tool.coverage.xml]
output = ".pytest_cache/coverage.xml"


[tool.coverage.run]
branch = true
source = ["template", "tests"]
omit = ["tests/fixtures/*"]
data_file = ".pytest_cache/.coverage"


[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "def __str__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "if typing.TYPE_CHECKING:",
]


[tool.poe.tasks]
lint_ruff = "ruff check template"
lint_mypy = "mypy template"
lint = ["lint_ruff", "lint_mypy"]
test = "pytest"
cover = "pytest --cov=template --cov-report xml"
fmt_ruff = "ruff format template"
fmt_black = "black template"
fmt = ["fmt_ruff", "fmt_black"]
build = ["fmt", "lint", "test"]
